version: "3.7"

services:

  nginx:
    build: ./
    container_name: nginx
    restart: always
    volumes:
      - cr-ssl-val:/app/ssl-folder
      - cr-letsencrypt-val:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"
networks: 
  default: 
    external: 
      name: external-example 


volumes: 
  cr-server-log:
        external: true
  generator-log:
        external: true
  fe-server-log:
        external: true
  cr-ssl-val:
        external: true
  cr-letsencrypt-val:
        external: true
  ssl-server-log:
        external: true

